name:                escape-the-room
version:             0.1.0.0
github:              "githubuser/escape-the-room"
license:             BSD3
author:              "Maksim Surkov"
maintainer:          "m.surkov@innopolis.ru"
copyright:           "2018 Maksim Surkov"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/modbrin/escape-the-room#readme>

ghc-options:
- -Wall -fno-warn-type-defaults

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  escape-the-room-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - escape-the-room

tests:
  escape-the-room-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - escape-the-room
